---
# Ansible playbook for a ansible-role-common

- name: Common stuff for all the server
  hosts: all
  become: true
  gather_facts: no
  roles:
    - labpositiva.common
  tags:
    - all
    - common
